name: ArgoCD Workflow

on:
  push:
    branches:
      - main
    paths:
      - result/*
      - .github/workflows/argocd/**
variables:
  imageRepository: "akyldocker25/voting-app-result"
  tag: "$(Build.BuildId)"

stages:
  - stage: Build
    displayName: Build and Push Docker Image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: self

          # Docker login, build and push
          - script: |
              echo "Logging into Docker Hub..."
              echo $(DOCKERHUB_PASSWORD) | docker login -u akyldocker25 --password-stdin

              echo "Building Docker image..."
              docker build -t $(imageRepository):$(tag) -t $(imageRepository):latest result/

              echo "Pushing Docker image..."
              docker push $(imageRepository):$(tag)
              docker push $(imageRepository):latest
            displayName: Build and Push Docker Image
            env:
              DOCKERHUB_PASSWORD: $(dockerhub_token) # Define in pipeline variable or secret

  - stage: Update
    displayName: Update Kubernetes Manifests
    dependsOn: Build
    jobs:
      - job: Update
        displayName: Update
        steps:
          - checkout: self
          - task: ShellScript@2
            inputs:
              scriptPath: "scripts/updateK8sManifests.sh"
              args: "vote $(imageRepository) $(tag)"

  - stage: Deploy
    displayName: Trigger ArgoCD Sync
    dependsOn: Update
    jobs:
      - job: Deploy
        displayName: Trigger ArgoCD
        steps:
          - checkout: self
          - script: |
              argocd login $(ARGOCD_SERVER) --username $(ARGOCD_USERNAME) --password $(ARGOCD_PASSWORD) --insecure
              argocd app sync $(ARGOCD_APP_NAME)
            displayName: Trigger ArgoCD Sync
